/**
 * @file    i2c.h
 * @brief   Blocking I2C master transport on LL with bounded waits.
 * @details Analogous to the project SPI layer, plus error reporting. The
 *          peripheral (I2Cx) must already be configured and enabled elsewhere
 *          (kernel clock, TIMINGR, pins); these helpers only drive
 *          transactions. Device addresses are 7-bit (unshifted).
 *
 *          Not reentrant: when several RTOS tasks share one bus, guard each
 *          call with a mutex on the application side.
 */

#ifndef I2C_H
#define I2C_H

/*==============================================================================
 *                              INCLUDED FILES
 *============================================================================*/

#include "stdint.h"

#include "stm32h7xx_ll_gpio.h"
#include "stm32h7xx_ll_i2c.h"

/*==============================================================================
 *                            MACRO DEFINITIONS
 *============================================================================*/

/* I2C_TIMEOUT / I2C_RECOVER_DELAY are defined in i2c.c and can be
   overridden there. */

/*==============================================================================
 *                               DATA TYPES
 *============================================================================*/

/**
 * @brief Transport and sensor-frame status codes.
 */
typedef enum {
    I2C_OK          = 0,  /**< Transaction completed                          */
    I2C_ERR_TIMEOUT = 1,  /**< Bus timeout, or device measurement not ready   */
    I2C_ERR_NACK    = 2,  /**< Device did not acknowledge (missing / busy)    */
    I2C_ERR_DATA    = 3   /**< Frame received but content invalid (CRC, skipped) */
} I2C_Status;

/*==============================================================================
 *                                VARIABLES
 *============================================================================*/

/* The transport keeps no state between transactions. */

/*==============================================================================
 *                           FUNCTION PROTOTYPES
 *============================================================================*/

/**
 * @brief   Write a byte buffer to a device.
 * @details Single transaction with AUTOEND (STOP generated by hardware).
 * @param[in,out] i2c  I2C peripheral instance.
 * @param[in]     addr 7-bit device address (unshifted).
 * @param[in]     data Bytes to send.
 * @param[in]     len  Number of bytes.
 * @return  I2C_OK, I2C_ERR_NACK or I2C_ERR_TIMEOUT.
 */
I2C_Status I2C_Write(I2C_TypeDef* i2c, uint8_t addr, const uint8_t* data, uint32_t len);

/**
 * @brief   Read a byte buffer from a device.
 * @param[in,out] i2c  I2C peripheral instance.
 * @param[in]     addr 7-bit device address (unshifted).
 * @param[out]    data Destination buffer, at least len bytes.
 * @param[in]     len  Number of bytes.
 * @return  I2C_OK, I2C_ERR_NACK or I2C_ERR_TIMEOUT.
 */
I2C_Status I2C_Read(I2C_TypeDef* i2c, uint8_t addr, uint8_t* data, uint32_t len);

/**
 * @brief   Register-style access: write, then repeated-start read.
 * @details Phase 1 sends wdata with SOFTEND (no STOP), phase 2 issues a
 *          repeated START and reads rlen bytes with AUTOEND.
 * @param[in,out] i2c   I2C peripheral instance.
 * @param[in]     addr  7-bit device address (unshifted).
 * @param[in]     wdata Bytes to send first (e.g. a register address).
 * @param[in]     wlen  Number of bytes to send.
 * @param[out]    rdata Destination buffer, at least rlen bytes.
 * @param[in]     rlen  Number of bytes to read.
 * @return  I2C_OK, I2C_ERR_NACK or I2C_ERR_TIMEOUT.
 */
I2C_Status I2C_WriteRead(I2C_TypeDef* i2c, uint8_t addr,
                         const uint8_t* wdata, uint32_t wlen,
                         uint8_t* rdata, uint32_t rlen);

/**
 * @brief   Unstick a bus where a slave holds SDA low.
 * @details Typical failure: the MCU resets in the middle of a read and the
 *          slave keeps driving SDA. Drives SCL as an open-drain GPIO for up
 *          to 9 clock pulses until the slave releases SDA, then generates a
 *          STOP condition. The pins are left in open-drain GPIO mode:
 *          reconfigure them back to the I2C alternate function and re-enable
 *          the peripheral afterwards.
 * @param[in,out] scl_port GPIO port of the SCL line.
 * @param[in]     scl_pin  SCL pin mask (LL_GPIO_PIN_x).
 * @param[in,out] sda_port GPIO port of the SDA line.
 * @param[in]     sda_pin  SDA pin mask (LL_GPIO_PIN_x).
 * @return  I2C_OK when SDA is released, I2C_ERR_TIMEOUT otherwise.
 */
I2C_Status I2C_BusRecover(GPIO_TypeDef* scl_port, uint32_t scl_pin,
                          GPIO_TypeDef* sda_port, uint32_t sda_pin);

#endif /* I2C_H */
